name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install build dependencies
      run: sudo apt-get -y install libx11-dev libxmu-dev libxft-dev libxrender-dev libxrandr-dev libpng-dev libxpm-dev uthash-dev autoconf automake
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
